export const styles = {
  container: {
    flex: 1,
    backgroundColor: "#FFF",
    paddingRight: 16,
    paddingLeft: 16,
    paddingBottom: 16,
    paddingTop: 32,
  },
  photo: {
    width: "100%",
    height: 240,
    objectFit: "cover",
    borderRadius: 8,
    marginBottom: 32,
  },
  comment: {},
  avatar: {
    width: 28,
    height: 28,
    borderRadius: 50,
    objectFit: "cover",
    overflow: "hidden",
  },
  textContainer: {
    width: "100%",
    backgroundColor: "rgba(0, 0, 0, 0.03)",
    padding: 16,
    borderRadius: 6,
  },
  text: {
    fontFamily: "Roboto - regular",
    fontSize: 13,
    lineHeight: 18,
    color: "#212121",
  },
  data: {
    fontFamily: "Roboto - regular",
    fontSize: 10,
    lineHeight: 12,
    color: "#BDBDBD",
    textAlign: "right",
  },
  input: {
    height: 50,
    width: "100%",
    borderWidth: 1,
    borderColor: "#E8E8E8",
    borderRadius: 100,
    backgroundColor: "#F6F6F6",
    padding: 16,
    fontFamily: "Roboto - medium",
    color: "#BDBDBD",
    fontSize: 16,
    lineHeight: 19,
  },
  sendButton: {
    position: "absolute",
    right: 8,
    top: 8,
    width: 34,
    height: 34,
    backgroundColor: "#FF6C00",
    borderRadius: 50,
    justifyContent: "center",
    alignItems: "center",
  },
};
